apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::394773365544:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-JVAt2lxbokgM
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::394773365544:role/UdacityFlaskDeployCBKubectlRole
      username: build   
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-27T08:39:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1295"
  uid: d93ab794-e2c2-4185-8796-d223121a4316
